import {
  ArrowLeft,
  ArrowRight,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Eye,
  EyeOff,
  Loader,
  LogOut,
  Search,
  Star,
  Tags,
  X,
} from "lucide-react";

export const Icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  eye: Eye,
  eyeOff: EyeOff,
  logOut: LogOut,
  loader: Loader,
  search: Search,
  star: Star,
  tags: Tags,
  x: X,
};
