export const andrewHubermanPodcastList = [
  {
    title:
      "Charting the Architecture of the Universe & Human Life | Dr. Brian Keating",
    slug: "charting-the-architecture-of-the-universe-and-human-life-brian-keating",
    tags: ["Cosmology", "Astronomy", "Human Perception"],
    image:
      "charting-the-architecture-of-the-universe-and-human-life-brian-keating.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: false,
    videoId: "3-ukCGQJk2c",
    videoUploadedAt: "2025-01-20T12:00:00Z",
  },
  {
    title:
      "Overcoming Guilt & Building Tenacity in Kids & Adults | Dr. Becky Kennedy",
    slug: "overcoming-guilt-and-building-tenacity-in-kids-and-adults-becky-kennedy",
    tags: ["Parenting", "Emotional Intelligence", "Child Development"],
    image:
      "overcoming-guilt-and-building-tenacity-in-kids-and-adults-becky-kennedy.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "qi4VwpEs3LE",
    videoUploadedAt: "2025-01-13T12:00:00Z",
  },
  {
    title:
      "How to Use Curiosity & Focus to Create a Joyful & Meaningful Life | Dr. Bernardo Huberman",
    slug: "how-to-use-curiosity-and-focus-to-create-a-joyful-and-meaningful-life-bernardo-huberman",
    tags: ["Scientific Curiosity", "Work-Life Balance", "Physics"],
    image:
      "how-to-use-curiosity-and-focus-to-create-a-joyful-and-meaningful-life-bernardo-huberman.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "tR73Ny4Dt9s",
    videoUploadedAt: "2024-12-16T12:00:00Z",
  },
  {
    title: "The Art of Learning & Living Life | Josh Waitzkin",
    slug: "the-art-of-learning-and-living-life-josh-waitzkin",
    tags: ["Performance Psychology", "Learning Mastery", "Mental Training"],
    image: "the-art-of-learning-and-living-life-josh-waitzkin.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "wAnDWfEIwoE",
    videoUploadedAt: "2025-01-27T12:00:00Z",
  },
  {
    title:
      "How to Achieve True Happiness Using Science-Based Protocols | Dr. Laurie Santos",
    slug: "how-to-achieve-true-happiness-using-science-based-protocols-laurie-santos",
    tags: [
      "Science-Based Happiness",
      "Positive Psychology",
      "Mental Wellbeing",
    ],
    image:
      "how-to-achieve-true-happiness-using-science-based-protocols-laurie-santos.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "Phm-Alz1Zjo",
    videoUploadedAt: "2024-12-23T12:00:00Z",
  },
  {
    title: "How to Best Guide Your Life Decisions & Path | Dr. Jordan Peterson",
    slug: "how-to-best-guide-your-life-decisions-and-path-jordan-peterson",
    tags: ["Psychology", "Self-Improvement", "Neuroscience"],
    image: "how-to-best-guide-your-life-decisions-and-path-jordan-peterson.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "K0hkhbGYaGQ",
    videoUploadedAt: "2024-12-30T12:00:00Z",
  },
  {
    title:
      "How to Build Strength, Endurance & Flexibility at Any Age | Pavel Tsatsouline",
    slug: "how-to-build-strength-endurance-and-flexibility-at-any-age-pavel-tsatsouline",
    tags: ["Strength Training", "Fitness", "Longevity"],
    image:
      "how-to-build-strength-endurance-and-flexibility-at-any-age-pavel-tsatsouline.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "Z3OpxT65fKw",
    videoUploadedAt: "2025-02-10T12:00:00Z",
  },
  {
    title: "How to Make Better Decisions | Dr. Michael Platt",
    slug: "how-to-make-better-decisions-michael-platt",
    tags: ["Decision Making", "Neuroscience", "Social Psychology"],
    image: "how-to-make-better-decisions-michael-platt.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "bAWUYuygS_U",
    videoUploadedAt: "2025-02-17T12:00:00Z",
  },
  {
    title: "How to Enhance Your Immune System | Dr. Roger Seheult",
    slug: "how-to-enhance-your-immune-system-roger-seheult",
    tags: ["Immune Health", "Light Therapy", "Mitochondrial Health"],
    image: "how-to-enhance-your-immune-system-roger-seheult.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "N5DAW8mkJ6Y",
    videoUploadedAt: "2025-02-24T12:00:00Z",
  },
  {
    title: "How Different Diets Impact Your Health | Dr. Christopher Gardner",
    slug: "how-different-diets-impact-your-health-christopher-gardner",
    tags: ["Nutrition Science", "Diet Research", "Personalized Nutrition"],
    image: "how-different-diets-impact-your-health-christopher-gardner.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: false,
    videoId: "9vQZT2igXN4",
    videoUploadedAt: "2025-05-12T12:00:00Z",
  },
  {
    title:
      "How to Increase Your Speed, Mobility & Longevity with Plyometrics & Sprinting | Stuart McMillan",
    slug: "how-to-increase-your-speed-mobility-and-longevity-with-plyometrics-and-sprinting-stuart-mcmillan",
    tags: ["Movement Science", "Plyometric Training", "Fitness Longevity"],
    published: false,
    image:
      "how-to-increase-your-speed-mobility-and-longevity-with-plyometrics-and-sprinting-stuart-mcmillan.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "U3cSnzdyyXU",
    videoUploadedAt: "2025-03-17T12:00:00Z",
  },
  {
    title:
      "How to Improve Your Teeth & Oral Microbiome for Brain & Body Health | Dr. Staci Whitman",
    slug: "how-to-improve-your-teeth-and-oral-microbiome-for-brain-and-body-health-staci-whitman",
    tags: ["Oral Health", "Microbiome", "Preventive Health"],
    image:
      "how-to-improve-your-teeth-and-oral-microbiome-for-brain-and-body-health-staci-whitman.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "_oOEKKiwdDE",
    videoUploadedAt: "2025-03-24T12:00:00Z",
  },
  {
    title:
      "Transform Your Mental Health With Diet & Lifestyle | Dr. Chris Palmer",
    slug: "transform-your-mental-health-with-diet-and-lifestyle-chris-palmer",
    tags: ["Mental Health", "Mitochondria", "Metabolism"],
    published: false,
    image:
      "transform-your-mental-health-with-diet-and-lifestyle-chris-palmer.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "hCyvqRq5YmM",
    videoUploadedAt: "2025-03-31T12:00:00Z",
  },
  {
    title: "How to Achieve Inner Peace & Healing | Dr. Richard Schwartz",
    slug: "how-to-achieve-inner-peace-and-healing-richard-schwartz",
    tags: ["Internal Family Systems", "Self-Healing", "Trauma Recovery"],
    image: "how-to-achieve-inner-peace-and-healing-richard-schwartz.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "KuuoLT-fq4s",
    videoUploadedAt: "2025-03-03T12:00:00Z",
  },
  {
    title: "How to Find & Be a Great Romantic Partner | Lori Gottlieb",
    slug: "how-to-find-and-be-a-great-romantic-partner-lori-gottlieb",
    tags: ["Relationships", "Emotional Intelligence", "Psychology"],
    image: "how-to-find-and-be-a-great-romantic-partner-lori-gottlieb.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "lYK4UFf8mlc",
    videoUploadedAt: "2025-04-07T12:00:00Z",
  },
  {
    title:
      "Tools for Overcoming Substance & Behavioral Addictions | Ryan Soave",
    slug: "tools-for-overcoming-substance-and-behavioral-addictions-ryan-soave",
    tags: ["Addiction Recovery", "Neuroscience", "Mental Health"],
    image:
      "tools-for-overcoming-substance-and-behavioral-addictions-ryan-soave.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "J7yn4tJEmJU",
    videoUploadedAt: "2025-04-21T12:00:00Z",
  },
  {
    title: "How to Improve Your Vitality & Heal From Disease | Dr. Mark Hyman",
    slug: "improve-vitality-heal-from-disease-mark-hyman",
    tags: ["Functional Medicine", "Chronic Disease", "Preventive Health"],
    image: "improve-vitality-heal-from-disease-mark-hyman.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "UyneMnERmnI",
    videoUploadedAt: "2025-04-14T12:00:00Z",
  },
  {
    title: "What Pets Actually Want & Need | Dr. Karolina Westlund",
    slug: "what-pets-want-need-karolina-westlund",
    tags: ["Animal Psychology", "Pet Behavior", "Animal Welfare"],
    image: "what-pets-want-need-karolina-westlund.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: true,
    videoId: "6ck9fa6_C8c",
    videoUploadedAt: "2025-04-28T12:00:00Z",
  },
  {
    title:
      "Contracts of Love & Money That Make or Break Relationships | James Sexton",
    slug: "contracts-of-love-and-money-that-make-or-break-relationships-james-sexton",
    tags: ["Prenuptial Agreements", "Relationships", "Love and Money"],
    image:
      "contracts-of-love-and-money-that-make-or-break-relationships-james-sexton.jpg",
    podcastHost: "Andrew Huberman",
    isPremium: false,
    videoId: "zpkwefXtbfk",
    videoUploadedAt: "2025-05-05T12:00:00Z",
  },
];
