export const chrisWilliamsonPodcastList = [
  {
    title: "23 Lessons For Being Kinder To Yourself - Joe Hudson",
    slug: "23-lessons-for-being-kinder-to-yourself-joe-hudson",
    tags: [
      "Emotional Intelligence",
      "Self-Compassion",
      "Relationship Building",
    ],
    image: "23-lessons-for-being-kinder-to-yourself-joe-hudson.jpg",
    podcastHost: "Chris Williamson",
    isPremium: true,
    videoId: "p8ZhcYoW43s",
    videoUploadedAt: "2025-04-07T12:00:00Z",
  },
  {
    title: "Why Evolution Favours Beauty Over Survival - Matt Ridley",
    slug: "why-evolution-favours-beauty-over-survival-matt-ridley",
    tags: ["Sexual Selection", "Darwin's Theory", "Evolutionary Biology"],
    image: "why-evolution-favours-beauty-over-survival-matt-ridley.jpg",
    podcastHost: "Chris Williamson",
    isPremium: true,
    videoId: "ZZPKJWiWeNU",
    videoUploadedAt: "2025-04-03T12:00:00Z",
  },
  {
    title: "What Science Now Says About Consciousness - Annaka Harris",
    slug: "what-science-now-says-about-consciousness-annaka-harris",
    tags: ["Consciousness", "Philosophy of Mind", "Neuroscience"],
    image: "what-science-now-says-about-consciousness-annaka-harris.jpg",
    podcastHost: "Chris Williamson",
    isPremium: true,
    videoId: "M2DbhKDyo18",
    videoUploadedAt: "2025-04-12T12:00:00Z",
  },
  {
    title: "The Most Misleading Story About Young Men - William Costello",
    slug: "the-most-misleading-story-about-young-men-william-costello",
    tags: ["Masculinity", "Media Analysis", "Mental Health"],
    image: "the-most-misleading-story-about-young-men-william-costello.jpg",
    podcastHost: "Chris Williamson",
    isPremium: true,
    videoId: "NeL_jc1T_KI",
    videoUploadedAt: "2025-04-05T12:00:00Z",
  },
  {
    title: "How Modern Parenting Got It All Wrong - Dr Paul Turke",
    slug: "how-modern-parenting-got-it-all-wrong-dr-paul-turke",
    tags: ["Evolutionary Parenting", "Child Development", "Anthropology"],
    image: "how-modern-parenting-got-it-all-wrong-dr-paul-turke.jpg",
    podcastHost: "Chris Williamson",
    isPremium: true,
    videoId: "iOkLAsNmlJ0",
    videoUploadedAt: "2025-05-08T12:00:00Z",
  },
  {
    title: "How To Overcome The Worst Pain Of Your Life - Jeremy Renner",
    slug: "how-to-overcome-the-worst-pain-of-your-life-jeremy-renner",
    tags: ["Mental Resilience", "Recovery Journey", "Pain Management"],
    image: "how-to-overcome-the-worst-pain-of-your-life-jeremy-renner.jpg",
    podcastHost: "Chris Williamson",
    isPremium: false,
    videoId: "ZajzamaQJAA",
    videoUploadedAt: "2025-05-05T12:00:00Z",
  },
  {
    title: "How To Rewire Your Brain To Take More Risks - Alex Hutchinson",
    slug: "how-to-rewire-your-brain-to-take-more-risks-alex-hutchinson",
    tags: ["Exploration Psychology", "Brain Development", "Risk Taking"],
    image: "how-to-rewire-your-brain-to-take-more-risks-alex-hutchinson.jpg",
    podcastHost: "Chris Williamson",
    videoId: "WO151nmEl3g",
    isPremium: true,
    videoUploadedAt: "2025-05-03T12:00:00Z",
  },
  {
    title:
      "Limerence Explained: Why Do We Get Addicted To People? - Crappy Childhood Fairy",
    slug: "limerence-explained-why-do-we-get-addicted-to-people-crappy-childhood-fairy",
    tags: ["Psychology", "Attachment Theory", "Recovery"],
    image:
      "limerence-explained-why-do-we-get-addicted-to-people-crappy-childhood-fairy.jpg",
    podcastHost: "Chris Williamson",
    videoId: "BBthcu_nNlc",
    isPremium: true,
    videoUploadedAt: "2025-05-01T12:00:00Z",
  },
  {
    title: "How To Win The War Of The Future - Joe Lonsdale",
    slug: "how-to-win-the-war-of-the-future-joe-lonsdale",
    tags: ["Future Warfare", "Strategic Innovation", "Institutional Reform"],
    image: "how-to-win-the-war-of-the-future-joe-lonsdale.jpg",
    podcastHost: "Chris Williamson",
    videoId: "JMgPTMM2Gzs",
    isPremium: false,
    videoUploadedAt: "2025-04-28T12:00:00Z",
  },
  {
    title: "Why Are Liberal Women Becoming Unhappy? - Brad Wilcox",
    slug: "why-are-liberal-women-becoming-unhappy-brad-wilcox",
    tags: ["Marriage Happiness", "Gender Studies", "Cultural Politics"],
    image: "why-are-liberal-women-becoming-unhappy-brad-wilcox.jpg",
    podcastHost: "Chris Williamson",
    videoId: "u6okoAp5CX0",
    isPremium: true,
    videoUploadedAt: "2025-04-26T12:00:00Z",
  },
  {
    title: "Why Smart People Make Stupid Money Decisions - Dave Ramsey",
    slug: "why-smart-people-make-stupid-money-decisions-dave-ramsey",
    tags: ["Personal Finance", "Success Mindset", "Business Growth"],
    image: "why-smart-people-make-stupid-money-decisions-dave-ramsey.jpg",
    podcastHost: "Chris Williamson",
    videoId: "hcPAoEemLkg",
    isPremium: true,
    videoUploadedAt: "2025-04-24T12:00:00Z",
  },
  {
    title:
      "Harvard Professor Reveals The Secret To Lasting Love & Happiness - Arthur Brooks",
    slug: "harvard-professor-reveals-the-secret-to-lasting-love-and-happiness-arthur-brooks",
    tags: ["Love Psychology", "Relationship Science", "Happiness Research"],
    image:
      "harvard-professor-reveals-the-secret-to-lasting-love-and-happiness-arthur-brooks.jpg",
    podcastHost: "Chris Williamson",
    videoId: "jY1gwywkmvc",
    isPremium: true,
    videoUploadedAt: "2025-04-21T12:00:00Z",
  },
  {
    title: "Why Women Say They Want One Thing But Date Another - Rob Henderson",
    slug: "why-women-say-they-want-one-thing-but-date-another-rob-henderson",
    tags: ["Dating Psychology", "Gender Dynamics", "Mate Selection"],
    image:
      "why-women-say-they-want-one-thing-but-date-another-rob-henderson.jpg",
    podcastHost: "Chris Williamson",
    videoId: "Y7Y2Fs3zu0U",
    isPremium: true,
    videoUploadedAt: "2025-04-17T12:00:00Z",
  },
  {
    title: "How To Find The Love Of Your Life - Ty Tashiro",
    slug: "how-to-find-the-love-of-your-life-ty-tashiro",
    tags: ["Relationship Science", "Attachment Theory", "Partner Selection"],
    image: "how-to-find-the-love-of-your-life-ty-tashiro.jpg",
    podcastHost: "Chris Williamson",
    videoId: "8hI0LEkRqXk",
    isPremium: true,
    videoUploadedAt: "2025-04-10T12:00:00Z",
  },
  {
    title: "44 Harsh Truths About Human Nature - Naval Ravikant",
    slug: "44-harsh-truths-about-human-nature-naval-ravikant",
    tags: ["Personal Development", "Philosophy", "Success Mindset"],
    image: "44-harsh-truths-about-human-nature-naval-ravikant.jpg",
    podcastHost: "Chris Williamson",
    videoId: "KyfUysrNaco",
    isPremium: true,
    videoUploadedAt: "2025-03-31T12:00:00Z",
  },
  {
    title: "How To Defeat Your Social Media Addiction - Catherine Price",
    slug: "defeat-social-media-addiction-catherine-price",
    tags: ["Digital Wellness", "Technology Addiction", "Mindfulness"],
    image: "defeat-social-media-addiction-catherine-price.jpg",
    podcastHost: "Chris Williamson",
    videoId: "JHjhw8Ek3Zk",
    isPremium: true,
    videoUploadedAt: "2025-03-29T12:00:00Z",
  },
  {
    title: "Why Do We Date People That Need Fixing？ - Dr John Delony",
    slug: "fixing-relationships-john-delony",
    tags: ["Relationships", "Emotional Intelligence", "Self-Acceptance"],
    image: "fixing-relationships-john-delony.jpg",
    podcastHost: "Chris Williamson",
    videoId: "yscguH7dLbY",
    isPremium: true,
    videoUploadedAt: "2025-03-27T12:00:00Z",
  },
  {
    title: "How To Take Control Of Your Own Destiny - George Mack",
    slug: "take-control-of-your-own-destiny-george-mack",
    tags: ["High Agency", "Personal Development", "Decision Making"],
    image: "take-control-of-your-own-destiny-george-mack.jpg",
    podcastHost: "Chris Williamson",
    videoId: "iVl5FLRuGXI",
    isPremium: true,
    videoUploadedAt: "2025-03-24T12:00:00Z",
  },
  {
    title: "Why Do Modern Movies Suck So Much? - Critical Drinker",
    slug: "modern-movies-analysis-critical-drinker",
    tags: ["Film Industry", "Hollywood Trends", "Media Criticism"],
    image: "modern-movies-analysis-critical-drinker.jpg",
    podcastHost: "Chris Williamson",
    videoId: "PxIgDAc48qw",
    isPremium: true,
    videoUploadedAt: "2025-03-22T12:00:00Z",
  },
  {
    title:
      "The Art Of Effortless Confidence & Social Persuasion - Vanessa Van Edwards",
    slug: "effortless-confidence-social-persuasion-vanessa-van-edwards",
    tags: ["Body Language", "Social Psychology", "Charisma Techniques"],
    image: "effortless-confidence-social-persuasion-vanessa-van-edwards.jpg",
    podcastHost: "Chris Williamson",
    videoId: "ITxbwgyGh6w",
    isPremium: true,
    videoUploadedAt: "2025-03-20T12:00:00Z",
  },
  {
    title: "Why Modern Women Feel More Lost Than Ever - Freya India",
    slug: "why-modern-women-feel-lost-freya-india",
    tags: ["Therapy Culture", "Modern Femininity", "Relationship Psychology"],
    image: "why-modern-women-feel-lost-freya-india.jpg",
    podcastHost: "Chris Williamson",
    videoId: "wmU7VVxhERw",
    isPremium: true,
    videoUploadedAt: "2025-03-17T12:00:00Z",
  },
  {
    title: "The Art Of Unlocking Your Inner Peace - Yung Pueblo",
    slug: "unlocking-inner-peace-yung-pueblo",
    tags: ["Mindfulness", "Mental Health", "Self-Awareness"],
    image: "unlocking-inner-peace-yung-pueblo.jpg",
    podcastHost: "Chris Williamson",
    videoId: "NAxDJzd_meg",
    isPremium: true,
    videoUploadedAt: "2025-03-15T12:00:00Z",
  },
  {
    title: "Has Modern Society Set Women Up For Failure? - Louise Perry",
    slug: "has-modern-society-set-women-up-for-failure-louise-perry",
    tags: ["Fertility Decline", "Gender Dynamics", "Modern Parenting"],
    image: "has-modern-society-set-women-up-for-failure-louise-perry.jpg",
    podcastHost: "Chris Williamson",
    videoId: "NkSXtukw1VA",
    isPremium: true,
    videoUploadedAt: "2025-03-06T12:00:00Z",
  },
  {
    title:
      "The Science Of Emotional Intelligence & Self-Understanding - Dr Julie Smith",
    slug: "emotional-intelligence-self-understanding-julie-smith",
    tags: ["Emotional Intelligence", "Mental Health", "Self-Compassion"],
    image: "emotional-intelligence-self-understanding-julie-smith.jpg",
    podcastHost: "Chris Williamson",
    videoId: "-lDza7kSqvw",
    isPremium: true,
    videoUploadedAt: "2025-03-03T12:00:00Z",
  },
  {
    title: "The Secret Habits Of Supercommunicators - Charles Duhigg",
    slug: "super-communicators-secret-habits-charles-duhigg",
    tags: [
      "Communication Skills",
      "Emotional Intelligence",
      "Relationship Psychology",
    ],
    image: "super-communicators-secret-habits-charles-duhigg.jpg",
    podcastHost: "Chris Williamson",
    videoId: "ZOD-C67bUc4",
    isPremium: true,
    videoUploadedAt: "2025-03-01T12:00:00Z",
  },
  {
    title: "What Traits Should You Look For In A Partner? - Dr Shannon Curry",
    slug: "what-traits-to-look-for-in-partner-shannon-curry",
    tags: ["Relationships", "Psychology", "Partner Selection"],
    image: "what-traits-to-look-for-in-partner-shannon-curry.jpg",
    podcastHost: "Chris Williamson",
    videoId: "hDD3ZNUmEiQ",
    isPremium: true,
    videoUploadedAt: "2025-02-27T12:00:00Z",
  },
  {
    title:
      "Fear Is Running Your Life. Here's How To Break Free - Erwin McManus",
    slug: "break-free-from-fear-erwin-mcmanus",
    tags: ["Fear Management", "Personal Development", "Emotional Intelligence"],
    image: "break-free-from-fear-erwin-mcmanus.jpg",
    podcastHost: "Chris Williamson",
    videoId: "eBYC63aiqRU",
    isPremium: true,
    videoUploadedAt: "2025-02-22T12:00:00Z",
  },
  {
    title:
      "Evolution Played A Dirty Trick On Us - Why Modern Life Feels So Empty - William von Hippel",
    slug: "why-modern-life-feels-empty-william-von-hippel",
    tags: ["Evolution", "Social Connection", "Happiness"],
    image: "why-modern-life-feels-empty-william-von-hippel.jpg",
    podcastHost: "Chris Williamson",
    videoId: "B7An4jA2Wec",
    isPremium: true,
    videoUploadedAt: "2025-02-20T12:00:00Z",
  },
  {
    title:
      "The Psychological Secrets That Build Billion-Dollar Brands - Rory Sutherland (4K)",
    slug: "psychological-secrets-that-build-billion-dollar-brands-rory-sutherland",
    tags: ["Business Psychology", "Decision Making", "Consumer Behavior"],
    image:
      "psychological-secrets-that-build-billion-dollar-brands-rory-sutherland.jpg",
    podcastHost: "Chris Williamson",
    videoId: "qvpw4_O25eU",
    isPremium: true,
    videoUploadedAt: "2025-02-17T12:00:00Z",
  },
  {
    title:
      "The Science Of Rewiring Your Brain To Be Less Miserable - Dr Rick Hanson",
    slug: "rewiring-brain-for-happiness-rick-hanson",
    tags: ["Neuroscience", "Personal Development", "Brain Training"],
    image: "rewiring-brain-for-happiness-rick-hanson.jpg",
    podcastHost: "Chris Williamson",
    videoId: "IIcmtqHsD8g",
    isPremium: true,
    videoUploadedAt: "2025-02-15T12:00:00Z",
  },
  {
    title:
      "The Science Of Childhood Bullying & Adult Mental Health - Dr Tracy Vaillancourt",
    slug: "childhood-bullying-adult-mental-health-tracy-vaillancourt",
    tags: ["Bullying Prevention", "Mental Health", "Child Development"],
    image: "childhood-bullying-adult-mental-health-tracy-vaillancourt.jpg",
    podcastHost: "Chris Williamson",
    videoId: "RE4n29uEldA",
    isPremium: true,
    videoUploadedAt: "2025-02-13T12:00:00Z",
  },
  {
    title: "How One Year Of Focus Can Change Everything - Sahil Bloom",
    slug: "one-year-of-focus-sahil-bloom-key-takeaways",
    tags: ["Personal Development", "Life Philosophy", "Time Management"],
    image: "one-year-of-focus-sahil-bloom-key-takeaways.jpg",
    podcastHost: "Chris Williamson",
    videoId: "vR1BaN-7Yrk",
    isPremium: true,
    videoUploadedAt: "2025-02-06T12:00:00Z",
  },
  {
    title: "How To Fix Your Negative Patterns - Alain de Botton",
    slug: "fix-negative-patterns-alain-de-botton",
    tags: [
      "Emotional Intelligence",
      "Self-Awareness",
      "Relationship Psychology",
    ],
    image: "fix-negative-patterns-alain-de-botton.jpg",
    podcastHost: "Chris Williamson",
    videoId: "BQHo-z-pA8E",
    isPremium: true,
    videoUploadedAt: "2025-02-03T12:00:00Z",
  },
  {
    title: "How Nervous People Can Perform Under Pressure - Steve Magness",
    slug: "how-nervous-people-can-perform-under-pressure-steve-magness",
    tags: ["Performance Psychology", "Mental Toughness", "Stress Management"],
    image: "how-nervous-people-can-perform-under-pressure-steve-magness.jpg",
    podcastHost: "Chris Williamson",
    videoId: "s6bRXTvgVVw",
    isPremium: true,
    videoUploadedAt: "2025-02-01T12:00:00Z",
  },
  {
    title: "How To Design Your Life For Peak Creativity - Dan Koe",
    slug: "design-life-for-peak-creativity-dan-koe",
    tags: ["Life Design", "Creativity", "Personal Development"],
    image: "design-life-for-peak-creativity-dan-koe.jpg",
    podcastHost: "Chris Williamson",
    videoId: "xfi2O6xjr_w",
    isPremium: true,
    videoUploadedAt: "2025-01-25T12:00:00Z",
  },
  {
    title: "9 Ways People Destroy Their Own Relationships - Jillian Turecki",
    slug: "9-ways-people-destroy-relationships-jillian-turecki",
    tags: ["Relationships", "Self-Awareness", "Emotional Intelligence"],
    image: "9-ways-people-destroy-relationships-jillian-turecki.jpg",
    podcastHost: "Chris Williamson",
    videoId: "_DPyc6D9-Xs",
    isPremium: false,
    videoUploadedAt: "2025-01-23T12:00:00Z",
  },
  {
    title: "The Psychology Of Finding Meaning In Life - John Vervaeke",
    slug: "psychology-finding-meaning-life-john-vervaeke",
    tags: ["Meaning of Life", "Psychology", "Philosophy"],
    image: "psychology-finding-meaning-life-john-vervaeke.jpg",
    podcastHost: "Chris Williamson",
    videoId: "bfAlC2Tn0bg",
    isPremium: true,
    videoUploadedAt: "2025-01-18T12:00:00Z",
  },
  {
    title: "A Man's Guide To Mastering Your Emotions - Connor Beaton",
    slug: "mastering-your-emotions-connor-beaton",
    tags: ["Emotional Intelligence", "Men's Mental Health", "Self-Awareness"],
    image: "mastering-your-emotions-connor-beaton.jpg",
    podcastHost: "Chris Williamson",
    videoId: "YvDOLGoJrYQ",
    isPremium: true,
    videoUploadedAt: "2025-01-16T12:00:00Z",
  },
  {
    title: "How To Build An Extraordinary Life - Tony Robbins",
    slug: "build-extraordinary-life-tony-robbins",
    tags: ["Success Mindset", "Tony Robbins", "Life Transformation"],
    image: "build-extraordinary-life-tony-robbins.jpg",
    podcastHost: "Chris Williamson",
    videoId: "eeU1fNZ2pZA",
    isPremium: true,
    videoUploadedAt: "2025-01-13T12:00:00Z",
  },
  {
    title:
      "How To Stop Betraying Yourself & Be More Authentic - David Sutcliffe",
    slug: "stop-betraying-yourself-be-more-authentic-david-sutcliffe",
    tags: ["Authenticity", "Self-Awareness", "Relationships"],
    image: "stop-betraying-yourself-be-more-authentic-david-sutcliffe.jpg",
    podcastHost: "Chris Williamson",
    videoId: "tCcEgF2qRO0",
    isPremium: false,
    videoUploadedAt: "2025-01-11T12:00:00Z",
  },
  {
    title: "The Key Strategies Of Behaviour Change - Dr Rangan Chatterjee",
    slug: "behavior-change-strategies-rangan-chatterjee",
    tags: ["Behavior Change", "Self-Awareness", "Mental Health"],
    image: "behavior-change-strategies-rangan-chatterjee.jpg",
    podcastHost: "Chris Williamson",
    videoId: "qBcH7puhMo8",
    isPremium: false,
    videoUploadedAt: "2025-01-09T12:00:00Z",
  },
  {
    title: "Destroy Your Mental Limits & Unlock Your Best Self - Adam Grant",
    slug: "destroy-mental-limits-unlock-best-self-adam-grant",
    tags: ["Growth Mindset", "Psychology", "Personal Development"],
    image: "destroy-mental-limits-unlock-best-self-adam-grant.jpg",
    podcastHost: "Chris Williamson",
    videoId: "DLfWv_Ey27s",
    isPremium: false,
    videoUploadedAt: "2025-01-04T12:00:00Z",
  },
  {
    title: "How To Put Yourself First Without Feeling Guilty - Nick Pollard",
    slug: "put-yourself-first-without-feeling-guilty-nick-pollard",
    tags: ["Boundaries", "Self-Care", "Personal Development"],
    image: "put-yourself-first-without-feeling-guilty-nick-pollard.jpg",
    podcastHost: "Chris Williamson",
    videoId: "mqtdA2F-XxU",
    isPremium: false,
    videoUploadedAt: "2025-01-02T12:00:00Z",
  },
  {
    title: "How To Fix Your Sleep & Supercharge Your Life - Dr Matthew Walker",
    slug: "fix-sleep-supercharge-life-matthew-walker",
    tags: ["Sleep Science", "Health", "Neuroscience"],
    image: "fix-sleep-supercharge-life-matthew-walker.jpg",
    podcastHost: "Chris Williamson",
    videoId: "Hf_NTmu2uvg",
    isPremium: false,
    videoUploadedAt: "2024-12-30T12:00:00Z",
  },
  {
    title: "How To Focus On What Matters Most - Greg McKeown",
    slug: "focus-on-what-matters-most-greg-mckeown",
    tags: ["Essentialism", "Focus Strategies", "Success Management"],
    image: "focus-on-what-matters-most-greg-mckeown.jpg",
    podcastHost: "Chris Williamson",
    videoId: "ZDJiIFc3Mj8",
    isPremium: false,
    videoUploadedAt: "2024-12-21T12:00:00Z",
  },
  {
    title: "15 Harsh Truths From History’s Greatest Founders - David Senra",
    slug: "15-harsh-truths-from-greatest-founders-david-senra",
    tags: ["Entrepreneurship", "Founder Mindset", "Success Principles"],
    image: "15-harsh-truths-from-greatest-founders-david-senra.jpg",
    podcastHost: "Chris Williamson",
    videoId: "p_8KKY8fQdA",
    isPremium: false,
    videoUploadedAt: "2024-12-16T12:00:00Z",
  },
  {
    title: "How To Think Like History’s Greatest Genius - Michael Gelb",
    slug: "think-like-historys-greatest-genius-michael-gelb",
    tags: ["Leonardo da Vinci", "Creative Thinking", "Personal Development"],
    image: "think-like-historys-greatest-genius-michael-gelb.jpg",
    podcastHost: "Chris Williamson",
    videoId: "B2bHy6o7i1A",
    isPremium: false,
    videoUploadedAt: "2024-12-12T12:00:00Z",
  },
  {
    title: "Pushing The Boundaries Of Mental Toughness - Nedd Brockman",
    slug: "pushing-boundaries-mental-toughness-nedd-brockman",
    tags: ["Mental Toughness", "Endurance Running", "Resilience"],
    image: "pushing-boundaries-mental-toughness-nedd-brockman.jpg",
    podcastHost: "Chris Williamson",
    videoId: "tGdpAipQpI0",
    isPremium: false,
    videoUploadedAt: "2024-12-09T12:00:00Z",
  },
  {
    title: "The Invisible Psychology Of Happiness & Meaning - Lionel Page",
    slug: "invisible-psychology-happiness-meaning-lionel-page",
    tags: [
      "Evolutionary Psychology",
      "Happiness Research",
      "Social Comparison",
    ],
    image: "invisible-psychology-happiness-meaning-lionel-page.jpg",
    podcastHost: "Chris Williamson",
    videoId: "5bXDdrG4kw4",
    isPremium: false,
    videoUploadedAt: "2024-12-05T12:00:00Z",
  },
  {
    title: "Exercise Scientist’s Masterclass On Longevity - Dr Mike Israetel",
    slug: "longevity-masterclass-from-exercise-scientist-mike-israetel",
    tags: ["Longevity", "Fitness Science", "Anti-Aging"],
    image: "longevity-masterclass-from-exercise-scientist-mike-israetel.jpg",
    podcastHost: "Chris Williamson",
    videoId: "OUEaDmRQ_Ng",
    isPremium: false,
    videoUploadedAt: "2024-12-02T12:00:00Z",
  },
  {
    title: "Why Does Mainstream Media Suck So Much? - Dave Smith",
    slug: "why-mainstream-media-sucks-dave-smith",
    tags: ["Media Analysis", "Politics", "Independent Media"],
    image: "why-mainstream-media-sucks-dave-smith.jpg",
    podcastHost: "Chris Williamson",
    videoId: "u0Yv7rNj43o",
    isPremium: false,
    videoUploadedAt: "2024-11-30T12:00:00Z",
  },
  {
    title: "Life Lessons From A Modern Cowboy - Dry Creek Dewayne",
    slug: "life-lessons-from-modern-cowboy-dry-creek-dewayne",
    tags: ["Cowboy Wisdom", "Emotional Intelligence", "Personal Development"],
    image: "life-lessons-from-modern-cowboy-dry-creek-dewayne.jpg",
    podcastHost: "Chris Williamson",
    videoId: "YB8ma6fmb1A",
    isPremium: false,
    videoUploadedAt: "2024-11-25T12:00:00Z",
  },
  {
    title: "The Hidden Truth About Our Collapsing Birth Rates - Mads Larsen",
    slug: "hidden-truth-about-collapsing-birth-rates-mads-larsen",
    tags: ["Birth Rates", "Evolutionary Psychology", "Modern Dating"],
    image: "hidden-truth-about-collapsing-birth-rates-mads-larsen.jpg",
    podcastHost: "Chris Williamson",
    videoId: "7fL_xEBYTDs",
    isPremium: false,
    videoUploadedAt: "2024-11-23T12:00:00Z",
  },
  {
    title:
      "Motivation, Discipline & Getting Through Hard Times - Jesse James West",
    slug: "motivation-discipline-getting-through-hard-times-jesse-james-west",
    tags: ["Mental Toughness", "Personal Development", "Authentic Living"],
    image:
      "motivation-discipline-getting-through-hard-times-jesse-james-west.jpg",
    podcastHost: "Chris Williamson",
    videoId: "NkwNpKjeYyo",
    isPremium: false,
    videoUploadedAt: "2024-11-18T12:00:00Z",
  },
];
