export const davidPerellPodcastList = [
  {
    title: "The Case Against Writing with AI — Ezra Klein",
    slug: "case-against-writing-with-ai-ezra-klein",
    tags: ["Writing Process", "Journalism", "Artificial Intelligence"],
    image: "case-against-writing-with-ai-ezra-klein.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "smb7hy6KufQ",
    videoUploadedAt: "2025-05-28T12:01:41Z",
  },

  {
    title: "Dean Koontz: 120 Novels Published. 500M Copies Sold.",
    slug: "dean-koontz-120-novels-published-500m-copies-sold",
    tags: ["Creative Writing", "Writing Process", "Author Insights"],
    image: "dean-koontz-120-novels-published-500m-copies-sold.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "DqqedlVDCeQ",
    videoUploadedAt: "2025-05-07T12:00:21Z",
  },

  {
    title: "Harvard Professor Explains The Rules of Writing — Steven Pinker",
    slug: "harvard-professor-explains-rules-writing-steven-pinker",
    tags: ["Writing Skills", "Academic Writing", "Steven Pinker"],
    image: "harvard-professor-explains-rules-writing-steven-pinker.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "nBQPnvmaNcE",
    videoUploadedAt: "2025-06-04T12:01:27Z",
  },
  {
    title: "Learn Writing from an Oscar Winner — Eric Roth",
    slug: "learn-writing-from-oscar-winner-eric-roth",
    tags: ["Screenwriting", "Creative Writing", "Storytelling"],
    image: "learn-writing-from-oscar-winner-eric-roth.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "SUND6hATgzA",
    videoUploadedAt: "2025-05-21T12:00:49Z",
  },
  {
    title: "A New Way To Think About Writing — Paul Harding",
    slug: "new-way-think-about-writing-paul-harding",
    tags: ["Creative Writing", "Writing Process", "Storytelling Techniques"],
    image: "new-way-think-about-writing-paul-harding.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "roLRPQPQU58",
    videoUploadedAt: "2025-06-11T13:03:49Z",
  },
];
