export const davidPerellPodcastList = [
  {
    title: "You’ve Never Seen Writing Visualized Like This — Michael Dean",
    slug: "writing-visualized-michael-dean",
    tags: ["Writing Skills", "Content Creation", "Communication"],
    image: "writing-visualized-michael-dean.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "t1elm49zcQg",
    videoUploadedAt: "2025-04-09T12:01:25Z",
  },
  {
    title: "The 84-Minute Comedy Writing Masterclass — Michael Jamin",
    slug: "84-minute-comedy-writing-masterclass-michael-jamin",
    tags: ["Comedy Writing", "Storytelling", "Screenwriting"],
    image: "84-minute-comedy-writing-masterclass-michael-jamin.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "xH5N9M09Kn8",
    videoUploadedAt: "2025-05-14T12:01:40Z",
  },
  {
    title: "Learn a New Way of Storytelling in 72 Minutes — Will Storr",
    slug: "learn-new-way-storytelling-72-minutes-will-storr",
    tags: ["Storytelling", "Character Development", "Creative Writing"],
    image: "learn-new-way-storytelling-72-minutes-will-storr.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "kDrsYMW_EYg",
    videoUploadedAt: "2025-04-23T18:53:53Z",
  },
  {
    title: "The Case Against Writing with AI — Ezra Klein",
    slug: "case-against-writing-with-ai-ezra-klein",
    tags: ["Writing Process", "Journalism", "Artificial Intelligence"],
    image: "case-against-writing-with-ai-ezra-klein.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "smb7hy6KufQ",
    videoUploadedAt: "2025-05-28T12:01:41Z",
  },

  {
    title: "Dean Koontz: 120 Novels Published. 500M Copies Sold.",
    slug: "dean-koontz-120-novels-published-500m-copies-sold",
    tags: ["Creative Writing", "Writing Process", "Author Insights"],
    image: "dean-koontz-120-novels-published-500m-copies-sold.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "DqqedlVDCeQ",
    videoUploadedAt: "2025-05-07T12:00:21Z",
  },

  {
    title: "Harvard Professor Explains The Rules of Writing — Steven Pinker",
    slug: "harvard-professor-explains-rules-writing-steven-pinker",
    tags: ["Writing Skills", "Academic Writing", "Steven Pinker"],
    image: "harvard-professor-explains-rules-writing-steven-pinker.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "nBQPnvmaNcE",
    videoUploadedAt: "2025-06-04T12:01:27Z",
  },
  {
    title: "Learn Writing from an Oscar Winner — Eric Roth",
    slug: "learn-writing-from-oscar-winner-eric-roth",
    tags: ["Screenwriting", "Creative Writing", "Storytelling"],
    image: "learn-writing-from-oscar-winner-eric-roth.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "SUND6hATgzA",
    videoUploadedAt: "2025-05-21T12:00:49Z",
  },
  {
    title: "A New Way To Think About Writing — Paul Harding",
    slug: "new-way-think-about-writing-paul-harding",
    tags: ["Creative Writing", "Writing Process", "Storytelling Techniques"],
    image: "new-way-think-about-writing-paul-harding.jpg",
    podcastHost: "David Perell",
    isPremium: true,
    videoId: "roLRPQPQU58",
    videoUploadedAt: "2025-06-11T13:03:49Z",
  },
];
