export const edMylettPodcastList = [
  {
    title:
      "If You Want To Have A Good Quality of Life , DO THIS! Feat. Brie Bauer",
    slug: "good-quality-life–brie-bauer",
    tags: ["Resilience", "Overcoming Adversity", "Life Lessons"],
    image: "good-quality-life–brie-bauer.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "7gtu7mAcciw",
    videoUploadedAt: "2024-12-24T09:00:07Z",
  },
  {
    title:
      "If You Focus On THESE 4 Things, You Will DRAMATICALLY Impact Your Health! Feat. Peter Diamandis",
    slug: "focus-on-these-4-things-dramatically-impact-your-health-peter-diamandis",
    tags: ["Longevity Science", "Health Optimization", "Anti Aging"],
    image:
      "focus-on-these-4-things-dramatically-impact-your-health-peter-diamandis.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "z4eQEDTy3gQ",
    videoUploadedAt: "2025-01-07T09:00:58Z",
  },
  {
    title:
      "If You Are AFRAID To Chase Your Dreams, Just Do THIS! Feat. Heidi Somers Guzman",
    slug: "chase-your-dreams-heidi-somers-guzman",
    tags: ["Entrepreneurship", "Personal Development", "Self Love"],
    image: "chase-your-dreams-heidi-somers-guzman.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "M8H207riZ1s",
    videoUploadedAt: "2025-01-28T09:00:32Z",
  },
  {
    title:
      "How to Manage Emotions Before They Manage You! Feat. Dr. Ethan Kross",
    slug: "manage-emotion-before-they-manage-you-ethan-kross",
    tags: ["Emotional Intelligence", "Psychology", "Self Improvement"],
    image: "manage-emotion-before-they-manage-you-ethan-kross.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "7LmdvuCjEgI",
    videoUploadedAt: "2024-12-31T09:00:06Z",
  },
  {
    title: "PROOF That Your Past Doesn’t Define Your Future Feat. Titus O'Neil",
    slug: "proof-that-your-past-does-not-defiine-your-future-titus-oneil",
    tags: ["Personal Development", "Overcoming Adversity", "Fatherhood"],
    image: "proof-that-your-past-does-not-defiine-your-future-titus-oneil.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "DZYOwMOWohc",
    videoUploadedAt: "2025-01-21T17:23:04Z",
  },
  {
    title: "Is Your Gut Controlling Your Mind? Feat. Dr. Steven Gundry",
    slug: "gut-controlling-mind-steven-gundry",
    tags: ["Gut Health", "Mental Health", "Microbiome"],
    image: "gut-controlling-mind-steven-gundry.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "FoAji-JOARQ",
    videoUploadedAt: "2025-02-18T09:00:30Z",
  },
  {
    title:
      "Stop Making Excuses About Your Past and Take Control Of Winning Today! Feat. Eric Thomas",
    slug: "stop-making-excuses-about-your-past-take-control-winning-today–eric-thomas",
    tags: ["Personal Development", "Mindset Mastery", "Overcoming Adversity"],
    image:
      "stop-making-excuses-about-your-past-take-control-winning-today–eric-thomas.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "hY6qildcjok",
    videoUploadedAt: "2024-12-17T09:00:42Z",
  },
  {
    title:
      "When You Understand THIS About Intelligence, It Will UNLOCK Your Potential Feat. Howard Gardner",
    slug: "understand-this-about-intelligence-unlock-potential-howard-gardner",
    tags: ["Multiple Intelligences", "Personal Development", "Human Potential"],
    image:
      "understand-this-about-intelligence-unlock-potential-howard-gardner.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "5_0UpobX1IM",
    videoUploadedAt: "2025-03-04T09:00:06Z",
  },
  {
    title:
      "If You're Going Through A Tough Time Right Now, You NEED To Hear This! Feat. Matt Long",
    slug: "going-through-tough-time-hear-this-matt-long",
    tags: [
      "Overcoming Adversity",
      "Mental Resilience",
      "Inspirational Stories",
    ],
    image: "going-through-tough-time-hear-this-matt-long.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "kTbGALrMvP8",
    videoUploadedAt: "2025-02-04T09:00:45Z",
  },
  {
    title:
      "The Harsh Truth About Money & Happiness That NO ONE Is Talking About Feat. Sahil Bloom",
    slug: "harsh-truth-about-money-happiness-sahil-bloom",
    tags: ["Life Design", "Personal Development", "Time Management"],
    image: "harsh-truth-about-money-happiness-sahil-bloom.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "xUXPCzh4_dk",
    videoUploadedAt: "2025-04-15T08:01:05Z",
  },
  {
    title: "Powerful Strategies To Deal with Narcissism and Addiction",
    slug: "powerful-strategies-deal-with-narcissism-addiction",
    tags: ["Narcissism", "Relationship Advice", "Mental Health"],

    image: "powerful-strategies-deal-with-narcissism-addiction.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "1MH9V2bMjzM",
    videoUploadedAt: "2025-03-22T08:00:04Z",
  },
  {
    title:
      "How To Make Time For The Things That Matter MOST Feat. Brendon Burchard",
    slug: "make-time-for-things-that-matter-most-brendon-burchard",
    tags: ["Time Management", "High Performance", "Productivity Hacks"],
    image: "make-time-for-things-that-matter-most-brendon-burchard.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "D7lBVZMRif8",
    videoUploadedAt: "2025-04-05T08:00:19Z",
  },
  {
    title: "Attachment Styles EXPLAINED: Which One Are You? Feat. Thais Gibson",
    slug: "attachment-styles-explained-thais-gibson",
    tags: ["Attachment Theory", "Relationships", "Emotional Health"],
    image: "attachment-styles-explained-thais-gibson.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "V0GPXg8Eqjk",
    videoUploadedAt: "2025-04-12T08:00:27Z",
  },
  {
    title: "Dangers of AI and Humanity's Future (Are You Ready?)",
    slug: "dangers-ai-humanity-future-are-you-ready",
    tags: [
      "Artificial Intelligence",
      "Future Technology",
      "Economic Disruption",
    ],
    image: "dangers-ai-humanity-future-are-you-ready.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "onSn0PRfy5Y",
    videoUploadedAt: "2025-05-03T08:01:01Z",
  },
  {
    title:
      "#1 Researcher: You May Have High Functioning Depression But Don't Know It Yet! Ft. Dr. Judith Joseph",
    slug: "high-functioning-depression-judith-joseph",
    tags: [
      "Mental Health",
      "High Functioning Depression",
      "Personal Development",
    ],
    image: "high-functioning-depression-judith-joseph.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "VQgT1BfjiEI",
    videoUploadedAt: "2025-04-22T08:00:35Z",
  },
  {
    title:
      "How to Stay Calm and In Control When Talking to Difficult People Feat. Jefferson Fisher",
    slug: "stay-calm-in-control-when-talking-difficult-people-jefferson-fisher",
    tags: [
      "Communication Skills",
      "Conflict Resolution",
      "Emotional Intelligence",
    ],

    image:
      "stay-calm-in-control-when-talking-difficult-people-jefferson-fisher.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "ad2oHBH_SXk",
    videoUploadedAt: "2025-04-01T08:00:01Z",
  },
  {
    title: "How To Unleash The Story of Greatness That Lives Within YOU",
    slug: "unleash-story-of-greatness-that-lives-within-you",
    tags: ["Personal Development", "Motivation", "Self-Improvement"],
    image: "unleash-story-of-greatness-that-lives-within-you.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "HRnPYP2J1Tk",
    videoUploadedAt: "2025-03-15T08:00:23Z",
  },
  {
    title:
      "Leadership in the AI Age: You Need To Adapt or Get Left Behind! Feat. Brendon Burchard",
    slug: "leadership-ai-age-adapt-or-get-left-behind-brendon-burchard",
    tags: [
      "Leadership Development",
      "Artificial Intelligence",
      "Team Management",
    ],
    image: "leadership-ai-age-adapt-or-get-left-behind-brendon-burchard.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "WZcCBJC2_ZQ",
    videoUploadedAt: "2025-03-13T08:00:33Z",
  },
  {
    title:
      "Why Most People Fail After Success—And How to Avoid It Feat. Molly Fletcher",
    slug: "why-most-people-fail-after-success-molly-fletcher",
    tags: ["Personal Development", "Peak Performance", "Success Mindset"],
    image: "why-most-people-fail-after-success-molly-fletcher.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "6uHnKBsajHg",
    videoUploadedAt: "2025-03-18T08:00:05Z",
  },
  {
    title: "Watch This If You're Tired Of Being BROKE! Feat. Morgan Housel",
    slug: "tired-being-broke-morgan-housel",
    tags: ["Money Mindset", "Wealth Building", "Personal Finance"],
    image: "tired-being-broke-morgan-housel.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "_jrriM2lYro",
    videoUploadedAt: "2025-03-25T08:00:30Z",
  },
  {
    title:
      "Former Navy SEAL Reveals Weird TRICK To Overcome FEAR & DO HARD STUFF | Rich Diviney",
    slug: "former-navy-seal-reveals-weird-trick-overcome-fear-do-hard-stuff-rich-diviney",
    tags: ["Personal Development", "Mental Resilience", "Leadership"],
    image:
      "former-navy-seal-reveals-weird-trick-overcome-fear-do-hard-stuff-rich-diviney.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "0G5nz8DYrNg",
    videoUploadedAt: "2025-04-08T08:00:00Z",
  },
  {
    title:
      "You’re Losing Influence Online—Here’s Why (And How To Fix It!) Feat. Andrew Brodsky",
    slug: "losing-influence-online-why-how-to-fix-andrew-brodsky",
    tags: [
      "Virtual Communication",
      "Professional Development",
      "Digital Leadership",
    ],
    image: "losing-influence-online-why-how-to-fix-andrew-brodsky.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "nzzL6Qaoiiw",
    videoUploadedAt: "2025-04-24T08:00:55Z",
  },
  {
    title:
      "You Don’t Need To SELL Your Company To Make A LOT of Money, You Need To Do This! Ft. Dave Whorton",
    slug: "you-dont-need-to-sell-your-company-to-make-money-you-need-to-do-this-dave-whorton",
    tags: ["Evergreen Business", "Entrepreneurship", "Business Strategy"],
    published: false,
    image:
      "you-dont-need-to-sell-your-company-to-make-money-you-need-to-do-this-dave-whorton.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "6XuEynZhkek",
    videoUploadedAt: "2025-04-29T08:00:08Z",
  },
  {
    title:
      "THIS Is Why High Achievers Are Secretly Struggling (and What To Do About It!) Ft. MARTHA BECK",
    slug: "why-high-achievers-struggling-martha-beck",
    tags: ["Anxiety Management", "Personal Development", "High Performance"],
    image: "why-high-achievers-struggling-martha-beck.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "Fhj3CfDoPlg",
    videoUploadedAt: "2025-05-06T08:00:24Z",
  },
  {
    title:
      "If You Want TO Live As LONG As Humanly Possible, Don't Forget To Focus on This!",
    slug: "if-you-want-to-live-as-long-as-possible-focus-on-this",
    tags: ["Biohacking", "Longevity", "Personal Development"],
    image: "if-you-want-to-live-as-long-as-possible-focus-on-this.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "SV1AM_ATd-U",
    videoUploadedAt: "2025-05-13T08:00:28Z",
  },
  {
    title:
      "If You Are On A Mission, You Need A TEAM That Has THIS Feat. Jon Gordon",
    slug: "if-you-are-on-mission-you-need-team-that-has-this-jon-gordon",
    tags: ["Team Building", "Leadership Development", "Personal Growth"],
    image: "if-you-are-on-mission-you-need-team-that-has-this-jon-gordon.jpg",
    podcastHost: "Ed Mylett",
    isPremium: true,
    videoId: "bY-rrOSfgg0",
    videoUploadedAt: "2025-05-20T08:00:50Z",
  },
];
