export const jayClousePodcastList = [
  {
    title: "Meet the Woman Who Built a $100M Online Education Empire",
    slug: "meet-woman-who-built-100m-online-education-empire",
    tags: ["Online Courses", "Digital Marketing", "Course Creation"],
    image: "meet-woman-who-built-100m-online-education-empire.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "sstH8GEdpTE",
    videoUploadedAt: "2024-08-09T14:14:26Z",
  },
  {
    title: "Meet YouTube's Secret Title Guru (100 Million Views)",
    slug: "meet-youtube-secret-title-guru-100-million-views",
    tags: ["YouTube Marketing", "Content Creation", "Video Titles"],
    image: "meet-youtube-secret-title-guru-100-million-views.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "53aIQJ3N2x4",
    videoUploadedAt: "2024-05-10T16:47:22Z",
  },
  {
    title: "Meet the Secret Strategist Behind Alex Hormozi and GaryVee",
    slug: "meet-secret-strategist-behind-alex-hormozi-gary-vee",
    tags: ["Content Strategy", "Brand Building", "Social Media Marketing"],
    image: "meet-secret-strategist-behind-alex-hormozi-gary-vee.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "U33bAgqIZAU",
    videoUploadedAt: "2025-05-06T18:01:16Z",
  },
  {
    title: "How to Make Merch That Doesn’t Suck",
    slug: "how-to-make-merch-that-does-not-suck",
    tags: ["Creator Economy", "Product Development", "YouTube Business"],
    image: "how-to-make-merch-that-does-not-suck.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "XsKIWRbfcxM",
    videoUploadedAt: "2024-10-31T18:27:12Z",
  },
  {
    title: "Meet the Woman Making Creators Millions with Chatbots",
    slug: "meet-woman-making-creators-millions-with-chatbots",
    tags: [
      "Social Media Marketing",
      "Marketing Automation",
      "Content Creator Business",
    ],
    image: "meet-woman-making-creators-millions-with-chatbots.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "ZQuYs6L_qn0",
    videoUploadedAt: "2024-11-27T13:49:11Z",
  },
];
