export const jayClousePodcastList = [
  {
    title: "How to Hire a YouTube Editor",
    slug: "how-to-hire-youtube-editor",
    tags: ["YouTube Editing", "Content Creation", "Freelance Hiring"],
    image: "how-to-hire-youtube-editor.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "JGwWrm0GSQg",
    videoUploadedAt: "2024-04-18T00:38:04Z",
  },
  {
    title: "How He Made $819,000 in 3 Years (With a Small Audience)",
    slug: "how-he-made-819k-in-3-years-with-small-audience",
    tags: ["Course Creation", "Digital Marketing", "Entrepreneurship"],
    image: "how-he-made-819k-in-3-years-with-small-audience.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "F0fZnJs3Sso",
    videoUploadedAt: "2024-12-28T16:00:15Z",
  },
  {
    title: "Meet the Best Selling Author Crushing YouTube (Mark Manson)",
    slug: "meet-best-selling-author-crushing-youtube-mark-manson",
    tags: ["YouTube Strategy", "Creator Economy", "Digital Entrepreneurship"],
    image: "meet-best-selling-author-crushing-youtube-mark-manson.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "XXRv6K5nl5A",
    videoUploadedAt: "2025-02-07T16:36:32Z",
  },
  {
    title: "Meet the YouTuber Who Solved Shorts (Jenny Hoyos Interview)",
    slug: "meet-youtuber-who-solved-shorts-jenny-hoyos-interview",
    tags: ["YouTube Shorts", "Content Creation", "Viral Content"],
    image: "meet-youtuber-who-solved-shorts-jenny-hoyos-interview.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "As7abwNhG7Y",
    videoUploadedAt: "2023-10-09T23:07:20Z",
  },
  {
    title: "Meet YouTube's Next Golden Boy (Dodford Interview)",
    slug: "meet-youtube-next-golden-boy-dodford-interview",
    tags: ["YouTube Strategy", "Content Creation", "Creative Process"],
    image: "meet-youtube-next-golden-boy-dodford-interview.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "R3fLyo7gyao",
    videoUploadedAt: "2023-12-04T22:50:13Z",
  },
  {
    title:
      "The Hidden Opportunity in Tutorial Channels (Thomas Frank Interview)",
    slug: "hidden-opportunity-tutorial-channels-thomas-frank-interview",
    tags: ["YouTube Strategy", "Tutorial Channels", "Content Creation"],
    image: "hidden-opportunity-tutorial-channels-thomas-frank-interview.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "AmAm9BRvTf4",
    videoUploadedAt: "2024-02-29T22:29:03Z",
  },
  {
    title: "What He Learned from Working With 10,000 Creators",
    slug: "what-he-learned-from-working-with-10000-creators",
    tags: ["Content Creation", "Creator Economy", "YouTube Strategy"],
    published: false,
    image: "what-he-learned-from-working-with-10000-creators.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "ksSFvuIuqSY",
    videoUploadedAt: "2024-07-09T18:49:32Z",
  },
  {
    title:
      "The Insane Logistics of YouTube's Biggest Production (Challenge Accepted)",
    slug: "insane-logistics-youtube-biggest-production-challenge-accepted",
    tags: ["YouTube Strategy", "Content Creation", "Video Production"],
    image: "insane-logistics-youtube-biggest-production-challenge-accepted.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "R-MOBBwxC3U",
    videoUploadedAt: "2024-12-20T22:59:41Z",
  },
  {
    title: "Meet the Woman Who Built a $100M Online Education Empire",
    slug: "meet-woman-who-built-100m-online-education-empire",
    tags: ["Online Courses", "Digital Marketing", "Course Creation"],
    image: "meet-woman-who-built-100m-online-education-empire.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "sstH8GEdpTE",
    videoUploadedAt: "2024-08-09T14:14:26Z",
  },
  {
    title: "Meet YouTube's Secret Title Guru (100 Million Views)",
    slug: "meet-youtube-secret-title-guru-100-million-views",
    tags: ["YouTube Marketing", "Content Creation", "Video Titles"],
    image: "meet-youtube-secret-title-guru-100-million-views.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "53aIQJ3N2x4",
    videoUploadedAt: "2024-05-10T16:47:22Z",
  },
  {
    title: "Meet the Secret Strategist Behind Alex Hormozi and GaryVee",
    slug: "meet-secret-strategist-behind-alex-hormozi-gary-vee",
    tags: ["Content Strategy", "Brand Building", "Social Media Marketing"],
    image: "meet-secret-strategist-behind-alex-hormozi-gary-vee.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "U33bAgqIZAU",
    videoUploadedAt: "2025-05-06T18:01:16Z",
  },
  {
    title: "How to Make Merch That Doesn’t Suck",
    slug: "how-to-make-merch-that-does-not-suck",
    tags: ["Creator Economy", "Product Development", "YouTube Business"],
    image: "how-to-make-merch-that-does-not-suck.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "XsKIWRbfcxM",
    videoUploadedAt: "2024-10-31T18:27:12Z",
  },
  {
    title: "Meet the Woman Making Creators Millions with Chatbots",
    slug: "meet-woman-making-creators-millions-with-chatbots",
    tags: [
      "Social Media Marketing",
      "Marketing Automation",
      "Content Creator Business",
    ],
    image: "meet-woman-making-creators-millions-with-chatbots.jpg",
    podcastHost: "Jay Clouse",
    isPremium: true,
    videoId: "ZQuYs6L_qn0",
    videoUploadedAt: "2024-11-27T13:49:11Z",
  },
];
