export const nathanBarryPodcastList = [
  {
    title: "Founder Success Story: From Side Hustle To Online Food Empire",
    slug: "founder-success-story-from-side-hustle-to-online-food-empire",
    tags: ["Content Creation", "Email Marketing", "Brand Building"],
    image: "founder-success-story-from-side-hustle-to-online-food-empire.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "VdRijLT13YM",
    videoUploadedAt: "2025-06-05T16:00:53Z",
  },
  {
    title: "How To Turn Podcast Guesting Into a $1M Business",
    slug: "turn-podcast-guesting-into-1m-business",
    tags: ["Podcast Marketing", "Business Growth", "Entrepreneurship"],
    image: "turn-podcast-guesting-into-1m-business.jpg",
    podcastHost: "Scott D. Clary",
    isPremium: false,
    videoId: "pN9t_kvMqEg",
    videoUploadedAt: "2025-05-22T16:00:43Z",
  },
  {
    title: "Building Creator Agencies to $10M/Year with Sahil Bloom",
    slug: "building-creator-agencies-10m-per-year-sahil-bloom",
    tags: ["Creator Economy", "Business Strategy", "Entrepreneurship"],
    image: "building-creator-agencies-10m-per-year-sahil-bloom.jpg",
    podcastHost: "Nathan Barry",
    isPremium: false,
    videoId: "D0RpsWEFsr4",
    videoUploadedAt: "2024-02-15T17:00:13Z",
  },
  {
    title:
      "Personal Branding Expert: The Bad Habit That’s Costing You Millions of Dollars",
    slug: "personal-branding-expert-bad-habits-costing-millions-dollars",
    tags: ["Personal Branding", "Entrepreneurship", "Leadership Development"],
    image: "personal-branding-expert-bad-habits-costing-millions-dollars.jpg",
    podcastHost: "Nathan Barry",
    isPremium: false,
    videoId: "4vF1bKfOLso",
    videoUploadedAt: "2024-03-28T17:00:03Z",
  },
  {
    title: "How To Write Great Books That Make Money For Decades | Tim Grahl",
    slug: "write-great-books-make-money-for-decades-tim-grahl",
    tags: ["Book Publishing", "Content Marketing", "Long Term Wealth"],
    image: "write-great-books-make-money-for-decades-tim-grahl.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "W0EniCvxF3Q",
    videoUploadedAt: "2024-01-18T20:00:18Z",
  },
  {
    title: "Expert Advice: 3 Tips to Make $100,000 Writing Books in 2024",
    slug: "3-tips-make-100k-writing-books-2024",
    tags: ["Self Publishing", "Author Business", "Publishing Strategy"],
    image: "3-tips-make-100k-writing-books-2024.jpg",
    podcastHost: "Nathan Barry",
    isPremium: false,
    videoId: "_3BI3XUdRTE",
    videoUploadedAt: "2024-05-09T16:00:32Z",
  },
  {
    title: "How to Make $2,000,000 From Courses and Quit Your 9-To-5",
    slug: "make-2-million-from-courses-quit-9-to-5",
    tags: ["Course Creation", "Online Business", "Content Marketing"],
    image: "make-2-million-from-courses-quit-9-to-5.jpg",
    podcastHost: "Nathan Barry",
    isPremium: false,
    videoId: "ixhcKz3covQ",
    videoUploadedAt: "2024-09-05T16:00:42Z",
  },
  {
    title:
      "5 Best Strategies to Scale Creator Products FAST | Startup Investor Reveals",
    slug: "5-best-strategies-scale-creator-products-fast-startup-investor-reveals",
    tags: ["Creator Economy", "Business Strategy", "Product Development"],
    image:
      "5-best-strategies-scale-creator-products-fast-startup-investor-reveals.jpg",
    podcastHost: "Nathan Barry",
    isPremium: false,
    videoId: "huV3hCVAwdI",
    videoUploadedAt: "2024-08-15T16:00:45Z",
  },
  {
    title:
      "7 Proven Methods to Scale Your $500,000 Creator Business in 90 Days",
    slug: "7-proven-methods-scale-500k-creator-business-90-days",
    tags: ["Creator Economy", "Business Scaling", "Revenue Growth"],
    image: "7-proven-methods-scale-500k-creator-business-90-days.jpg",
    podcastHost: "Nathan Barry",
    isPremium: false,
    videoId: "83X4Vr_5sXU",
    videoUploadedAt: "2024-05-23T16:00:06Z",
  },
  {
    title:
      "How Your Business Can Make $1,000,000 From Partnerships (in 60 Days)",
    slug: "how-your-business-can-make-1-million-from-partnerships-in-60-days",
    tags: ["Affiliate Marketing", "Business Growth", "Partnership Strategy"],
    image:
      "how-your-business-can-make-1-million-from-partnerships-in-60-days.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "RFuatO81oTA",
    videoUploadedAt: "2025-02-13T17:00:28Z",
  },
  {
    title: "How to Build a $100,000 Personal Brand (In Just 90 Days)",
    slug: "build-100k-personal-brand-in-90-days",
    tags: ["Personal Branding", "Founder Marketing", "Content Strategy"],
    image: "build-100k-personal-brand-in-90-days.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "VNKcZsWJQh8",
    videoUploadedAt: "2025-02-06T17:00:25Z",
  },
  {
    title: "The NEW Way to Become a Full-Time Creator in 12 Months (or less)",
    slug: "new-way-become-full-time-creator-12-months",
    tags: ["Creator Economy", "Content Creation", "Career Development"],
    image: "new-way-become-full-time-creator-12-months.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "DrGJYp16hKo",
    videoUploadedAt: "2025-01-16T17:00:14Z",
  },
  {
    title: "How to Pick a Business You ACTUALLY Enjoy (In 64 Mins)",
    slug: "how-to-pick-a-business-you-actually-enjoy-in-64-minutes",
    tags: ["Business Strategy", "Entrepreneurship", "Decision Making"],
    image: "how-to-pick-a-business-you-actually-enjoy-in-64-minutes.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "6jxxv7kmlbo",
    videoUploadedAt: "2025-02-20T17:00:15Z",
  },
  {
    title: "Building a $2,000,000 Business Plan for a Creator in 62 Mins",
    slug: "building-2m-business-plan-creator-62-minutes",
    tags: ["Creator Business", "Revenue Optimization", "Business Strategy"],
    image: "building-2m-business-plan-creator-62-minutes.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "AeRwjH73QSU",
    videoUploadedAt: "2025-01-23T17:00:16Z",
  },
  {
    title: "How I Made $7,000,000 from Instagram in 18 Months",
    slug: "made-7m-from-instagram-18-months",
    tags: ["Content Marketing", "Hospitality Business", "Entrepreneurship"],
    image: "made-7m-from-instagram-18-months.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "AxH5pWpe3Rc",
    videoUploadedAt: "2025-01-09T17:00:11Z",
  },
  {
    title:
      "How to Build a $100,000 Online Community in 3 Easy Steps | Mighty Networks Founder",
    slug: "build-100k-online-community-3-easy-steps-mighty-networks-founder",
    tags: ["Community Building", "Creator Economy", "Network Effects"],
    image:
      "build-100k-online-community-3-easy-steps-mighty-networks-founder.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "nnG5bP02kGU",
    videoUploadedAt: "2025-01-30T17:00:54Z",
  },
  {
    title: "Turn Your Writing Into A $1.7 Million Business In 2025",
    slug: "turn-writing-into-1-7-million-business-in-2025",
    tags: ["Creator Economy", "Business Building", "Writing Strategy"],
    image: "turn-writing-into-1-7-million-business-in-2025.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "2yNZP3EntYU",
    videoUploadedAt: "2024-11-14T17:00:03Z",
  },
  {
    title: "How to Turn Your Passion Into a Creator Business ($1Million+)",
    slug: "turn-passion-into-creator-business-1m-plus",
    tags: ["Creator Economy", "Audience Building", "Online Business"],
    image: "turn-passion-into-creator-business-1m-plus.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "jN8JM6zulM0",
    videoUploadedAt: "2024-12-12T17:00:46Z",
  },
  {
    title:
      "How I Built a $375,000 Business Working 15 Hours per Week (Full Guide)",
    slug: "built-375k-business-working-15-hours-per-week-full-guide",
    tags: ["Business Growth", "Paid Advertising", "Digital Products"],
    image: "built-375k-business-working-15-hours-per-week-full-guide.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "WSu7hkCtSLk",
    videoUploadedAt: "2024-12-19T17:00:27Z",
  },
  {
    title: "Inside Mark Manson's $2,500,000 Creator Business | Full Breakdown",
    slug: "inside-mark-manson-2-5-million-creator-business-full-breakdown",
    tags: ["Creator Economy", "Business Strategy", "Content Marketing"],
    image: "inside-mark-manson-2-5-million-creator-business-full-breakdown.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "GbtlsdEuygo",
    videoUploadedAt: "2024-12-05T17:00:15Z",
  },
  {
    title: "My 3-Step Formula for Introductions That Sell | Clay Hebert",
    slug: "3-step-formula-for-introductions-that-sell-clay-hebert",
    tags: ["Business Communication", "Personal Branding", "Networking Skills"],
    image: "3-step-formula-for-introductions-that-sell-clay-hebert.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "syuYfk093ps",
    videoUploadedAt: "2024-11-21T17:00:54Z",
  },
  {
    title:
      "7 Principles That Eliminated 90% of My Competition | 0 to $1M (Jay Papasan)",
    slug: "7-principles-eliminated-90-percent-competition-jay-papasan",
    tags: ["Business Strategy", "Book Writing", "Entrepreneurship"],
    image: "7-principles-eliminated-90-percent-competition-jay-papasan.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "ivoJhT98PZs",
    videoUploadedAt: "2024-10-18T16:00:57Z",
  },
  {
    title: "How To Make $100,000+ With 0 Employees (Full Guide)",
    slug: "make-100k-plus-with-0-employees-full-guide",
    tags: ["Solo Entrepreneurship", "Creator Business", "Business Strategy"],
    image: "make-100k-plus-with-0-employees-full-guide.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "atY6pYYv3gw",
    videoUploadedAt: "2024-11-07T17:00:06Z",
  },
  {
    title:
      "Every Single Thing I’m Doing to Launch My $5,000 Course | Full Guide",
    slug: "launch-5k-course-full-guide",
    tags: ["Course Launch", "Product Positioning", "Creator Business"],
    published: false,
    image: "launch-5k-course-full-guide.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "LOg2LhISE_A",
    videoUploadedAt: "2024-10-31T17:00:18Z",
  },
  {
    title:
      "The Subtle Art of Building a $100k - $1M Creator Business | Mark Manson",
    slug: "subtle-art-of-building-100k-1m-creator-business-mark-manson",
    tags: ["Creator Economy", "Business Strategy", "Content Creation"],
    image: "subtle-art-of-building-100k-1m-creator-business-mark-manson.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "t3ANEzd_XvI",
    videoUploadedAt: "2024-10-10T16:00:53Z",
  },
  {
    title:
      "How to Turn Your YouTube Channel Into a $100,000+ Business (2024) | Jo Franco",
    slug: "turn-youtube-channel-into-100k-plus-business-jo-franco",
    tags: ["Creator Economy", "YouTube Strategy", "Business Growth"],
    image: "turn-youtube-channel-into-100k-plus-business-jo-franco.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "2sSN9i4qRfE",
    videoUploadedAt: "2024-10-25T16:00:03Z",
  },
  {
    title: "The 7-Step Framework To Build a $30K/Month Coaching Business",
    slug: "7-step-framework-build-30k-per-month-coaching-business",
    tags: ["Group Coaching", "Premium Pricing", "Business Coaching"],
    image: "7-step-framework-build-30k-per-month-coaching-business.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "jjuhWvqkUPk",
    videoUploadedAt: "2025-05-01T16:01:13Z",
  },
  {
    title: "From Brain Surgery to $1.6M: How I Built My Dream Business",
    slug: "from-brain-surgery-to-1-6-million-how-i-built-my-dream-business",
    tags: ["Creator Economy", "Email Marketing", "Resilience"],
    image:
      "from-brain-surgery-to-1-6-million-how-i-built-my-dream-business.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "Nqy1C6_VAYg",
    videoUploadedAt: "2025-04-24T16:00:39Z",
  },
  {
    title: "Build a $25K/Month Software Business (Full Strategy)",
    slug: "build-25k-per-month-software-business–full-strategy",
    tags: ["SaaS Growth", "Direct Sales", "Creator Economy"],
    image: "build-25k-per-month-software-business–full-strategy.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "Aa_FgXxd2Oc",
    videoUploadedAt: "2025-03-06T17:00:10Z",
  },
  {
    title: "How This Musician Makes $500K/year Working 2 Hours A Week",
    slug: "how-this-musician-makes-500k-per-year-working-2-hours-a-week",

    tags: ["Passive Income", "Content Creation", "Creative Productivity"],
    image: "how-this-musician-makes-500k-per-year-working-2-hours-a-week.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "-GfPvVy-48U",
    videoUploadedAt: "2025-04-10T16:00:01Z",
  },
  {
    title: "Live Coaching: How To Grow An Agency to $2M",
    slug: "live-coaching-how-to-grow-an-agency-to-2-million-dollars",
    tags: ["Agency Growth", "Revenue Strategy", "Creator Economy"],
    image: "live-coaching-how-to-grow-an-agency-to-2-million-dollars.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "Fd7lpIakx2Q",
    videoUploadedAt: "2025-05-08T16:00:25Z",
  },
  {
    title: "Success Story: How to Scale a Coaching Business to $1M+",
    slug: "success-story-scale-coaching-business-1-million-plus",
    tags: ["Coaching Business", "Revenue Growth", "Business Scaling"],
    image: "success-story-scale-coaching-business-1-million-plus.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "BneY4d-Rkm8",
    videoUploadedAt: "2025-04-03T16:00:24Z",
  },
  {
    title: "Our Risky Branding Strategy Changed Everything",
    slug: "our-risky-branding-strategy-changed-everything",
    tags: ["Rebranding", "Creator Economy", "Brand Strategy"],
    image: "our-risky-branding-strategy-changed-everything.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "GonN-ggBRtM",
    videoUploadedAt: "2025-03-13T17:00:15Z",
  },
  {
    title: "How I Get Paid To Travel in 2025 & How You Can Too",
    slug: "how-i-get-paid-to-travel-in-2025-and-how-you-can-too",
    tags: ["Travel Business", "Content Creation", "Passive Income"],
    image: "how-i-get-paid-to-travel-in-2025-and-how-you-can-too.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "bLal1sml6gw",
    videoUploadedAt: "2025-03-27T17:00:40Z",
  },
  {
    title: "How AI Can Grow Your Business in 2025 (Expert Advice)",
    slug: "how-ai-can-grow-your-business-in-2025-expert-advice",
    tags: ["Artificial Intelligence", "Business Growth", "Workflow Automation"],
    image: "how-ai-can-grow-your-business-in-2025-expert-advice.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "rQb0QugA4pU",
    videoUploadedAt: "2025-04-17T16:01:27Z",
  },
  {
    title: "How To Turn Your Podcast Into A Full-Time Business",
    slug: "how-to-turn-your-podcast-into-a-full-time-business",
    tags: ["Podcast Monetization", "Revenue Streams", "Creator Economy"],
    image: "how-to-turn-your-podcast-into-a-full-time-business.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "O1cWvPzxrx4",
    videoUploadedAt: "2025-05-15T14:00:30Z",
  },
];
