export const nathanBarryPodcastList = [
  {
    title: "From Brain Surgery to $1.6M: How I Built My Dream Business",
    slug: "from-brain-surgery-to-1-6-million-how-i-built-my-dream-business",
    tags: ["Creator Economy", "Email Marketing", "Resilience"],
    image:
      "from-brain-surgery-to-1-6-million-how-i-built-my-dream-business.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "Nqy1C6_VAYg",
    videoUploadedAt: "2025-04-24T16:00:39Z",
  },
  {
    title: "Build a $25K/Month Software Business (Full Strategy)",
    slug: "build-25k-per-month-software-business–full-strategy",
    tags: ["SaaS Growth", "Direct Sales", "Creator Economy"],
    image: "build-25k-per-month-software-business–full-strategy.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "Aa_FgXxd2Oc",
    videoUploadedAt: "2025-03-06T17:00:10Z",
  },
  {
    title: "How This Musician Makes $500K/year Working 2 Hours A Week",
    slug: "how-this-musician-makes-500k-per-year-working-2-hours-a-week",

    tags: ["Passive Income", "Content Creation", "Creative Productivity"],
    image: "how-this-musician-makes-500k-per-year-working-2-hours-a-week.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "-GfPvVy-48U",
    videoUploadedAt: "2025-04-10T16:00:01Z",
  },
  {
    title: "Live Coaching: How To Grow An Agency to $2M",
    slug: "live-coaching-how-to-grow-an-agency-to-2-million-dollars",
    tags: ["Agency Growth", "Revenue Strategy", "Creator Economy"],
    image: "live-coaching-how-to-grow-an-agency-to-2-million-dollars.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "Fd7lpIakx2Q",
    videoUploadedAt: "2025-05-08T16:00:25Z",
  },
  {
    title: "Success Story: How to Scale a Coaching Business to $1M+",
    slug: "success-story-scale-coaching-business-1-million-plus",
    tags: ["Coaching Business", "Revenue Growth", "Business Scaling"],
    image: "success-story-scale-coaching-business-1-million-plus.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "BneY4d-Rkm8",
    videoUploadedAt: "2025-04-03T16:00:24Z",
  },
  {
    title: "Our Risky Branding Strategy Changed Everything",
    slug: "our-risky-branding-strategy-changed-everything",
    tags: ["Rebranding", "Creator Economy", "Brand Strategy"],
    image: "our-risky-branding-strategy-changed-everything.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "GonN-ggBRtM",
    videoUploadedAt: "2025-03-13T17:00:15Z",
  },
  {
    title: "How I Get Paid To Travel in 2025 & How You Can Too",
    slug: "how-i-get-paid-to-travel-in-2025-and-how-you-can-too",
    tags: ["Travel Business", "Content Creation", "Passive Income"],
    image: "how-i-get-paid-to-travel-in-2025-and-how-you-can-too.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "bLal1sml6gw",
    videoUploadedAt: "2025-03-27T17:00:40Z",
  },
  {
    title: "How AI Can Grow Your Business in 2025 (Expert Advice)",
    slug: "how-ai-can-grow-your-business-in-2025-expert-advice",
    tags: ["Artificial Intelligence", "Business Growth", "Workflow Automation"],
    image: "how-ai-can-grow-your-business-in-2025-expert-advice.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "rQb0QugA4pU",
    videoUploadedAt: "2025-04-17T16:01:27Z",
  },
  {
    title: "How To Turn Your Podcast Into A Full-Time Business",
    slug: "how-to-turn-your-podcast-into-a-full-time-business",
    tags: ["Podcast Monetization", "Revenue Streams", "Creator Economy"],
    image: "how-to-turn-your-podcast-into-a-full-time-business.jpg",
    podcastHost: "Nathan Barry",
    isPremium: true,
    videoId: "O1cWvPzxrx4",
    videoUploadedAt: "2025-05-15T14:00:30Z",
  },
];
