export const paulMillerdPodcastList = [
  {
    title: "How To Embrace Change & Live Courageously - Derek Sivers",
    slug: "embrace-change-live-courageously-derek-sivers",
    tags: ["Personal Development", "Life Philosophy", "Unconventional Living"],
    image: "embrace-change-live-courageously-derek-sivers.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "oYkbh8Bj3jo",
    videoUploadedAt: "2023-02-27T14:00:28Z",
  },
  {
    title: "How To Embrace Change & Live Courageously - Derek Sivers",
    slug: "embrace-change-live-courageously-derek-sivers",
    tags: ["Personal Development", "Life Philosophy", "Unconventional Living"],
    image: "embrace-change-live-courageously-derek-sivers.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "oYkbh8Bj3jo",
    videoUploadedAt: "2023-02-27T14:00:28Z",
  },
  {
    title: "Walk Until the Day Gets Interesting — Bilal Zaidi",
    slug: "walk-until-day-gets-interesting-bilal-zaidi",
    tags: ["Career Development", "Personal Growth", "Entrepreneurship"],
    image: "walk-until-day-gets-interesting-bilal-zaidi.jpg",
    podcastHost: "Paul Millerd",
    isPremium: false,
    videoId: "wUBS_6FAfbs",
    videoUploadedAt: "2023-08-10T07:41:30Z",
  },
  {
    title:
      "How To Find Your True Desires — Luke Burgis | Pathless Path Podcast",
    slug: "find-true-desires-luke-burgis",
    tags: ["Personal Development", "Authentic Living", "Life Philosophy"],
    image: "find-true-desires-luke-burgis.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "oF4H_NuA-qk",
    videoUploadedAt: "2023-07-03T14:44:12Z",
  },
  {
    title: "From NASA to Non-Profit to Author!! Nina Simon",
    slug: "nasa-non-profit-author-nina-simon",
    tags: ["Career Change", "Personal Development", "Financial Freedom"],
    image: "nasa-non-profit-author-nina-simon.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "S7BaQ_4rNsU",
    videoUploadedAt: "2023-01-04T13:00:14Z",
  },
  {
    title: "Rugby to TikTok Star!? - Ben Mercer",
    slug: "rugby-tiktok-star–ben-mercer",
    tags: ["Career Transition", "Content Creation", "Professional Sports"],
    image: "rugby-tiktok-star–ben-mercer.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "76Qvz-OPfQM",
    videoUploadedAt: "2023-07-31T13:35:11Z",
  },
  {
    title: "Creating Luck On The Internet — Jovian Gautama",
    slug: "creating-luck-on-internet-jovian-gautama",
    tags: ["Career Development", "Remote Work", "Entrepreneurship"],
    image: "creating-luck-on-internet-jovian-gautama.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "oy6yI3GcS4U",
    videoUploadedAt: "2023-10-12T14:44:25Z",
  },
  {
    title: "Profit, Freedom, and Good Culture — Justin Jackson",
    slug: "profit-freedom-good-culture-justin-jackson",
    tags: ["Entrepreneurship", "Business Strategy", "Company Culture"],
    image: "profit-freedom-good-culture-justin-jackson.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "iQ6Zq6yv65U",
    videoUploadedAt: "2024-02-27T15:23:45Z",
  },
  {
    title: "I love what I do, should I take a break? David Pakman",
    slug: "i-love-what-i-do-should-i-take-a-break-david-pakman",
    tags: ["Creator Economy", "Work Life Balance", "Content Creation"],
    image: "i-love-what-i-do-should-i-take-a-break-david-pakman.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "lnn3vXh3-rU",
    videoUploadedAt: "2024-03-12T14:14:32Z",
  },
  {
    title: "Kids Like To Work — Matt Bateman, Teacher & Philosopher",
    slug: "kids-like-work-matt-bateman-teacher-philosopher",
    tags: ["Education Philosophy", "Child Development", "Work Ethic"],
    image: "kids-like-work-matt-bateman-teacher-philosopher.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "up4fHGtzmsk",
    videoUploadedAt: "2024-03-25T19:26:33Z",
  },
  {
    title: "From Law to #1 Poker Player? - Cate Hall",
    slug: "from-law-number-one-poker-player-cate-hall",
    tags: ["Career Change", "Personal Development", "Agency"],
    image: "from-law-number-one-poker-player-cate-hall.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "0xhaU1_70T4",
    videoUploadedAt: "2024-05-29T13:46:46Z",
  },
  {
    title: "Finding The True Work Of Your Life — Steve Schlafman & Matt Yao",
    slug: "finding-true-work-your-life-steve-schlafman-matt-yao",
    tags: ["Career Transition", "Personal Development", "Work Life Balance"],
    image: "finding-true-work-your-life-steve-schlafman-matt-yao.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "LLT9lFOubUc",
    videoUploadedAt: "2024-03-18T11:00:07Z",
  },
  {
    title: "How To Thrive In Your Second Act After 40: Henry Oliver",
    slug: "thrive-second-act-after-40-henry-oliver",
    tags: ["Late Bloomers", "Career Change", "Personal Development"],
    image: "thrive-second-act-after-40-henry-oliver.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "3BFtZ44UaMo",
    videoUploadedAt: "2024-04-01T11:43:43Z",
  },
  {
    title: "Taking Ownership of Your Life — Justin Welsh",
    slug: "taking-ownership-your-life-justin-welsh",
    tags: ["Entrepreneurship", "Solo Business", "Personal Development"],
    image: "taking-ownership-your-life-justin-welsh.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "93xvBq-88K0",
    videoUploadedAt: "2024-04-15T20:47:20Z",
  },
  {
    title: "The Essence of Good Work - Matt Yao and Paul",
    slug: "essence-good-work-matt-yao-paul",
    tags: ["Good Work", "Career Change", "Future of Work"],
    image: "essence-good-work-matt-yao-paul.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "Dd6gvKRd_KY",
    videoUploadedAt: "2024-12-05T23:00:11Z",
  },
  {
    title: "The Secret of Writing Great Books - Nat Eliason",
    slug: "secret-writing-great-books-nat-eliason",
    tags: ["Writing Career", "Self Publishing", "Fiction Writing"],
    image: "secret-writing-great-books-nat-eliason.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "iIZC6i2hel8",
    videoUploadedAt: "2025-05-14T15:18:20Z",
  },
  {
    title: "Wander With Wonder — Dom Francks",
    slug: "wander-with-wonder-dom-francks",
    tags: ["Career Transition", "Nature Connection", "Personal Development"],
    image: "wander-with-wonder-dom-francks.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "vvcVa9hghhk",
    videoUploadedAt: "2024-02-20T04:25:27Z",
  },
  {
    title: "Inner Peace For High Achievers — Joe Hudson",
    slug: "inner-peace-for-high-achievers-joe-hudson",
    tags: ["Personal Development", "Emotional Intelligence", "Inner Peace"],
    image: "inner-peace-for-high-achievers-joe-hudson.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "AEfP8vsO-pE",
    videoUploadedAt: "2023-12-11T22:14:45Z",
  },
  {
    title: "He’s the reason everyone has a garden now - Kevin Espiritu",
    slug: "he-reason-everyone-has-garden-now-kevin-espiritu",
    tags: ["Entrepreneurship", "Content Creation", "Creator Economy"],
    image: "he-reason-everyone-has-garden-now-kevin-espiritu.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "ZjLdqWAfzDU",
    videoUploadedAt: "2024-02-05T14:30:11Z",
  },
];
