export const paulMillerdPodcastList = [
    {
title: "The Essence of Good Work - Matt Yao and Paul",
slug: "essence-good-work-matt-yao-paul",
tags: ["Good Work", "Career Change", "Future of Work"],
image: "essence-good-work-matt-yao-paul.jpg",
podcastHost: "Paul Millerd",
isPremium: true,
videoId: "Dd6gvKRd_KY",
videoUploadedAt: "2024-12-05T23:00:11Z"
},
  {
    title: "The Secret of Writing Great Books - Nat Eliason",
    slug: "secret-writing-great-books-nat-eliason",
    tags: ["Writing Career", "Self Publishing", "Fiction Writing"],
    image: "secret-writing-great-books-nat-eliason.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "iIZC6i2hel8",
    videoUploadedAt: "2025-05-14T15:18:20Z",
  },
  {
    title: "Wander With Wonder — Dom Francks",
    slug: "wander-with-wonder-dom-francks",
    tags: ["Career Transition", "Nature Connection", "Personal Development"],
    image: "wander-with-wonder-dom-francks.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "vvcVa9hghhk",
    videoUploadedAt: "2024-02-20T04:25:27Z",
  },
  {
    title: "Inner Peace For High Achievers — Joe Hudson",
    slug: "inner-peace-for-high-achievers-joe-hudson",
    tags: ["Personal Development", "Emotional Intelligence", "Inner Peace"],
    image: "inner-peace-for-high-achievers-joe-hudson.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "AEfP8vsO-pE",
    videoUploadedAt: "2023-12-11T22:14:45Z",
  },
  {
    title: "He’s the reason everyone has a garden now - Kevin Espiritu",
    slug: "he-reason-everyone-has-garden-now-kevin-espiritu",
    tags: ["Entrepreneurship", "Content Creation", "Creator Economy"],
    image: "he-reason-everyone-has-garden-now-kevin-espiritu.jpg",
    podcastHost: "Paul Millerd",
    isPremium: true,
    videoId: "ZjLdqWAfzDU",
    videoUploadedAt: "2024-02-05T14:30:11Z",
  },
];
